theme: jekyll-theme-slate

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: 
      type: ""
    values:
      layout: "front"
      author: 
